#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat $COMMIT_MSG_FILE)

if echo "$COMMIT_MSG" | grep -q "feat:"; then
  npx standard-version --release-as minor
elif echo "$COMMIT_MSG" | grep -q "fix:"; then
  npx standard-version --release-as patch
else
  echo "Commit message does not indicate a version bump. Proceeding without bumping."
fi
